name: cxr-bin-cls
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - matplotlib=3.1.1
  - numpy=1.18.1
  - pillow=6.2.1
  - pip=19.3.1
  - python=3.7.6
  - pytorch=1.4.0
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - six=1.13.0
  - torchvision=0.5.0
